# ASP.NET Core (.NET Framework)
trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: 'NuGet packages'

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    includePreviewVersions: true

- task: NuGetCommand@2
  displayName: 'Restore'
  inputs:
    restoreSolution: '$(solution)'
  
- task: DotNetCoreCLI@2
  displayName: 'Build of projects'
  inputs:
    command: 'build'
    projects: '**/InvitationPage-backend.csproj, **/InvitationPageModel.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build of tests'
  inputs:
    command: 'build'
    projects: '**/*Tests.csproj'
  
- task: DotNetCoreCLI@2
  displayName: 'Unit Tests'
  inputs:
    command: 'test'
    projects: '**/*UnitTests.csproj'